version: "3.8"
services:

  devopsdb:
    image: sahithi0622/javaproject_dbimage
    ports:
      - "3306"
    deploy:
      replicas: 1

  application:
    image: sahithi0622/javaproject_appimage
    ports:
      - "8080"
    deploy:
      replicas: 2
    depends_on:
      - devopsdb
